name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: pitch-elvarika
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Configure Docker
      run: gcloud auth configure-docker
      
    - name: Build and Deploy Backend
      run: |
        cd server
        gcloud run deploy elvarika-backend \
          --source . \
          --region us-central1 \
          --allow-unauthenticated
